try {
    
} catch (error) {
    console.log(error);
}
finally{
    //ok
}